image: node:lts-alpine

include:
  - template: Security/SAST.gitlab-ci.yml

stages:
  - test
  - pages

sast:
  stage: test

pages:
  cache:
    paths:
      - node_modules/
  script:
    - npm install -g @angular/cli
    - npm install
    - npm run build
    - mkdir -p public
    - mv dist/trackify/* public/
  rules:
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
  artifacts:
    paths:
      - public
